#!/bin/bash
battery=(󰂃 󰁻 󰁼 󰁽 󰁾 󰁿 󰂀 󰂁 󰂂 󰁹 󰂄) 
capacity=$(< /sys/class/power_supply/BAT0/capacity)
status=$(< /sys/class/power_supply/BAT0/status)
date=$(date +"%a, %-d %b %H:%M")
if [[ $status == "Discharging" ]]; then
    for i in {0..9}; do
	if (($capacity >= $i*10 && $capacity < $i*10+10)); then
	    index=$i
	fi
    done
else
    index=10
fi
printf "${battery[index]}" "$capacity"%  \| "$date"
