#!/bin/bash
bat=(󰂃 󰁻 󰁼 󰁽 󰁾 󰁿 󰂀 󰂁 󰂂 󰁹 󰂄) 
cap=$(cat /sys/class/power_supply/BAT0/capacity)
date=$(date +"%a, %-d %b %H:%M")
if [ $(cat /sys/class/power_supply/BAT0/status) = "Discharging" ]; then
    for i in {0..9}; do
	if (($cap >= $i*10 && $cap < $i*10+10)); then
	    echo " ${bat[i]}" "$cap"% \| "$date"
	fi
    done
else
    echo " ${bat[10]} \|" "$date"
fi	   
